### ISSUE TITLE
Can not start swiv Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by b-slim** [yahoo/swiv#3]
After a fresh install of swiv i am getting the following error
```
 swiv --druid 52.33.252.237:8888
module.js:472
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/yahoo-swiv/node_modules/fs-promise/index.js:4:15)
```

you can see the versions of my stack here
```shell
[sbouguerra@HW13470 ~] npm i -g yahoo-swiv
/usr/local/bin/swiv -> /usr/local/lib/node_modules/yahoo-swiv/bin/swiv
/usr/local/lib
└─┬ yahoo-swiv@0.9.39
  ├── abbrev@1.0.9
  ├── accepts@1.3.3
  ├── ansi-regex@2.0.0
  ├── ansi-styles@2.2.1
  ├── any-promise@1.3.0
  ├── ap@0.2.0
  ├── argparse@1.0.7
  ├── array-flatten@1.1.1
  ├── asap@2.0.4
  ├── asn1@0.2.3
  ├── assert-plus@0.2.0
  ├── async@1.5.2
  ├── aws-sign2@0.6.0
  ├── aws4@1.4.1
  ├── balanced-match@0.4.2
  ├── basic-auth@1.0.4
  ├── bignumber.js@2.3.0
  ├── bl@1.1.2
  ├── body-parser@1.15.2
  ├── boom@2.10.1
  ├── brace-expansion@1.1.6
  ├── browser-filesaver@1.1.1
  ├── buffer-writer@1.0.1
  ├── bytes@2.4.0
  ├── caseless@0.11.0
  ├── chalk@1.1.3
  ├── chronoshift@0.5.7
  ├── clipboard@1.5.12
  ├── closest@0.0.1
  ├── combined-stream@1.0.5
  ├── commander@2.9.0
  ├── compressible@2.0.8
  ├─┬ compression@1.6.2
  │ └── bytes@2.3.0
  ├── concat-map@0.0.1
  ├── content-disposition@0.5.1
  ├── content-type@1.0.2
  ├── cookie@0.3.1
  ├── cookie-signature@1.0.6
  ├── core-js@1.2.7
  ├── core-util-is@1.0.2
  ├── cryptiles@2.0.5
  ├── d3@3.5.17
  ├─┬ dashdash@1.14.0
  │ └── assert-plus@1.0.0
  ├── debug@2.2.0
  ├── delayed-stream@1.0.0
  ├── delegate@3.0.1
  ├── depd@1.1.0
  ├── destroy@1.0.4
  ├── ecc-jsbn@0.1.1
  ├── ee-first@1.1.1
  ├── encodeurl@1.0.1
  ├── encoding@0.1.12
  ├── escape-html@1.0.3
  ├── escape-string-regexp@1.0.5
  ├── esprima@2.7.2
  ├── etag@1.7.0
  ├── express@4.14.0
  ├── extend@3.0.0
  ├── extsprintf@1.0.2
  ├── fbjs@0.8.4
  ├── finalhandler@0.5.0
  ├── forever-agent@0.6.1
  ├── form-data@1.0.0-rc4
  ├── forwarded@0.1.0
  ├── fresh@0.3.0
  ├── fs-promise@0.5.0
  ├── fs.realpath@1.0.0
  ├── generate-function@2.0.0
  ├── generate-object-property@1.2.0
  ├── generic-pool@2.4.2
  ├─┬ getpass@0.1.6
  │ └── assert-plus@1.0.0
  ├── glob@7.0.5
  ├── good-listener@1.1.7
  ├── graceful-fs@4.1.6
  ├── graceful-readlink@1.0.1
  ├── har-validator@2.0.6
  ├── has-ansi@2.0.0
  ├── hawk@3.1.3
  ├── hoek@2.16.3
  ├── hsts@1.0.0
  ├── http-errors@1.5.0
  ├── http-signature@1.1.1
  ├── iconv-lite@0.4.13
  ├── immutable@3.8.1
  ├── immutable-class@0.6.9
  ├── inflight@1.0.5
  ├── inherits@2.0.1
  ├── ipaddr.js@1.1.1
  ├── is-my-json-valid@2.13.1
  ├── is-property@1.0.2
  ├── is-stream@1.1.0
  ├── is-typedarray@1.0.0
  ├── isarray@1.0.0
  ├── isomorphic-fetch@2.2.1
  ├── isstream@0.1.2
  ├── jodid25519@1.0.2
  ├── js-tokens@1.0.3
  ├── js-yaml@3.6.1
  ├── jsbn@0.1.0
  ├── json-schema@0.2.2
  ├── json-stringify-safe@5.0.1
  ├── jsonfile@2.3.1
  ├── jsonpointer@2.0.0
  ├── jsprim@1.3.0
  ├── klaw@1.3.0
  ├── logger-tracker@0.0.23
  ├── loose-envify@1.2.0
  ├── lz-string@1.4.4
  ├── matches-selector@0.0.1
  ├── media-typer@0.3.0
  ├── merge-descriptors@1.0.1
  ├── methods@1.1.2
  ├── mime@1.3.4
  ├── mime-db@1.23.0
  ├── mime-types@2.1.11
  ├── minimatch@3.0.3
  ├── morgan@1.7.0
  ├── ms@0.7.1
  ├─┬ mysql@2.11.1
  │ ├── isarray@0.0.1
  │ └── readable-stream@1.1.14
  ├── mz@2.4.0
  ├── negotiator@0.6.1
  ├── node-fetch@1.6.0
  ├── node-spawn-server@1.0.1
  ├── node-uuid@1.4.7
  ├── nopt@3.0.6
  ├── numeral@1.5.3
  ├── oauth-sign@0.8.2
  ├── object-assign@4.1.0
  ├── on-finished@2.3.0
  ├── on-headers@1.0.1
  ├── once@1.3.3
  ├── packet-reader@0.2.0
  ├── parseurl@1.3.1
  ├── path-is-absolute@1.0.0
  ├── path-to-regexp@0.1.7
  ├── pg@6.1.0
  ├── pg-connection-string@0.1.3
  ├── pg-pool@1.4.0
  ├── pg-types@1.11.0
  ├── pgpass@1.0.1
  ├── pinkie@2.0.4
  ├── pinkie-promise@2.0.1
  ├── plywood@0.12.3
  ├── plywood-druid-requester@1.5.4
  ├── plywood-mysql-requester@1.3.1
  ├── plywood-postgres-requester@0.9.1
  ├── postgres-array@1.0.0
  ├── postgres-bytea@1.0.0
  ├── postgres-date@1.0.3
  ├── postgres-date-utc@1.0.3
  ├── postgres-interval@1.0.2
  ├── process-nextick-args@1.0.7
  ├── promise@7.1.1
  ├── proxy-addr@1.1.2
  ├── q@1.4.1
  ├── qajax@1.3.0
  ├── qs@6.2.0
  ├── range-parser@1.2.0
  ├── raw-body@2.1.7
  ├── react@15.3.0
  ├── react-addons-css-transition-group@15.3.0
  ├── react-dom@15.3.0
  ├── readable-stream@2.0.6
  ├── request@2.74.0
  ├── rimraf@2.5.4
  ├── select@1.0.6
  ├── semver@4.3.2
  ├── send@0.14.1
  ├── serve-static@1.11.1
  ├── setprototypeof@1.0.1
  ├── sntp@1.0.9
  ├── split@1.0.0
  ├── sprintf-js@1.0.3
  ├── sqlstring@2.0.1
  ├─┬ sshpk@1.9.2
  │ └── assert-plus@1.0.0
  ├── statuses@1.3.0
  ├── string_decoder@0.10.31
  ├── stringstream@0.0.5
  ├── strip-ansi@3.0.1
  ├── supports-color@2.0.0
  ├── thenify@3.2.0
  ├── thenify-all@1.6.0
  ├── through@2.3.8
  ├── tiny-emitter@1.1.0
  ├── tough-cookie@2.3.1
  ├── tunnel-agent@0.4.3
  ├── tweetnacl@0.13.3
  ├── type-is@1.6.13
  ├── ua-parser-js@0.7.10
  ├── unpipe@1.0.0
  ├── util-deprecate@1.0.2
  ├── utils-merge@1.0.0
  ├── vary@1.1.0
  ├── verror@1.3.6
  ├── walltime-repack@0.2.4
  ├── whatwg-fetch@1.0.0
  ├── wrappy@1.0.2
  ├── xmlhttprequest@1.8.0
  └── xtend@4.0.1

[sbouguerra@HW13470 ~] swiv --druid 52.33.252.237:8888
module.js:472
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/yahoo-swiv/node_modules/fs-promise/index.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[sbouguerra@HW13470 ~] swiv --example
module.js:472
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/yahoo-swiv/node_modules/fs-promise/index.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by pjain1** [comment]
I installed it using `npm i -g yahoo-swiv` and started the app, it worked for me. I have `fs-extra` dir inside `/usr/local/lib/node_modules/yahoo-swiv/node_modules/`. Probably, try removing directory `/usr/local/lib/node_modules/yahoo-swiv`  and reinstall.

**Comment by b-slim** [comment]
@pjain1 thanks that did not work. i had to manually install `fs-extra` via `npm i -g fs-extra`

**Comment by b-slim** [comment]
looking [here](https://github.com/yahoo/swiv/blob/master/package.json#L55) it is listed as a dev deps ? does that make sense ? looks like it need to be a dependency.
